package by.trepam.like_it.command;

public enum CommandName {
	LOGIN,
	LOGOUT,
	LOCALIZATION,
	REGISTRATION,
	CATEGORIES,
	CATEGORY,
	MESSAGE,
	RATE,
	SITEMAP,
	PERSONAL_ACCOUNT,
	ADD_ANSWER,
	ADD_CATEGORY,
	GOTO_CHANGE_CATEGORY,
	CHANGE_CATEGORY,
	DELETE_CATEGORY,
	ADD_MESSAGE,
	GOTO_CHANGE_MESSAGE, 
	CHANGE_MESSAGE, 
	DELETE_MESSAGE,
	GOTO_CHANGE_PERSONAL_ACCOUNT,
	CHANGE_PERSONAL_ACCOUNT
}
